<a href="https://colab.research.google.com/github/K-R-Reddy/MachineLearning/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#1) Perform arithmetic operations on NumPy arrays.

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
print("Array 1 :",a1,"\nArray 2 :",a2)
print("Addition :",a1+a2)
print("Subtraction :",a1-a2)
print("Multiplication :",a1*a2)
print("Division :",a1/a2)
print("Remainder :",a1%a2)


Array 1 : [1 2 3 4 5] 
Array 2 : [ 6  7  8  9 10]
Addition : [ 7  9 11 13 15]
Subtraction : [-5 -5 -5 -5 -5]
Multiplication : [ 6 14 24 36 50]
Division : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Remainder : [1 2 3 4 5]


#2) Write a script to compute the mean and standard deviation of a NumPy array.
numpy.mean(array_name) : It is used to find Mean of the array.<br>
numpy.std(array_name) : It is used to find the Standard deviation of the array.

In [ ]:
a3=np.array([1,2,3,4,5])
m=np.mean(a3)
s=np.std(a3)
print("Array :",a3)
print("Mean :",m)
print("Standard deviation : ",s)

Array : [1 2 3 4 5]
Mean : 3.0
Standard deviation :  1.4142135623730951


#3) Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
a4=np.array(range(10,51,5))
print("Array :",a4)

Array : [10 15 20 25 30 35 40 45 50]


#4) Reshape the array into a 2x4 matrix


In [ ]:
a5=np.array([1,2,3,4,5,6,7,8])
print("Array :",a5)
ra5=a5.reshape(2,4)
print("After reshape Array :\n",ra5)

Array : [1 2 3 4 5 6 7 8]
After reshape Array :
 [[1 2 3 4]
 [5 6 7 8]]


#5) Given the arr=np.array([[1,2,3],[4,5,6],[7,8,9]]):

In [20]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

##a) Extract the sub-matrix containing the last two rows and first two columns.

In [21]:
sm=arr[1: , :2]
print("Matrix :\n",arr)
print("Sub Matrix :\n",sm)

Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub Matrix :
 [[4 5]
 [7 8]]


##b) Replace all elements greater than 4 and 0.

In [22]:
print("Matrix :\n",arr)
arr[arr>4]=0
print("After Replacing with Zeros :")
print(arr)

Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After Replacing with Zeros :
[[1 2 3]
 [4 0 0]
 [0 0 0]]


#6) Create two 1D arrays:
####a=np.array([1,2,3])
####b=np.array([4,5,6])
#Perform element-wise addition, multiplication, and division.

In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Array 1 :",a,"\nArray 2 :",b)
print("Addition :",np.add(a,b))
print("Multiplication :",np.multiply(a,b))
print("Division :",np.divide(a,b))

Array 1 : [1 2 3] 
Array 2 : [4 5 6]
Addition : [5 7 9]
Multiplication : [ 4 10 18]
Division : [0.25 0.4  0.5 ]


#7) Create a random NumPy array of size(4,4).Compute:

In [16]:
a7=np.random.rand(4,4)
print(a7)

[[0.88027929 0.03105268 0.40805506 0.93893567]
 [0.84907711 0.75613408 0.67579054 0.90894346]
 [0.5525453  0.91430799 0.8430257  0.54713275]
 [0.82911277 0.6207448  0.09741423 0.77844644]]


##a) Mean of each column

In [17]:
print("Array :\n",a7)
m2=np.mean(a7,axis=0)
print("Mean :",m2)

Array :
 [[0.88027929 0.03105268 0.40805506 0.93893567]
 [0.84907711 0.75613408 0.67579054 0.90894346]
 [0.5525453  0.91430799 0.8430257  0.54713275]
 [0.82911277 0.6207448  0.09741423 0.77844644]]
Mean : [0.77775362 0.58055989 0.50607138 0.79336458]


##b) Maximum value of the entire array.

In [18]:
print("Array :\n",a7)
max_value=np.max(a7)
print("Maximum value of the entire array :",max_value)

Array :
 [[0.88027929 0.03105268 0.40805506 0.93893567]
 [0.84907711 0.75613408 0.67579054 0.90894346]
 [0.5525453  0.91430799 0.8430257  0.54713275]
 [0.82911277 0.6207448  0.09741423 0.77844644]]
Maximum value of the entire array : 0.9389356665431605


##c) Sum of all elements.

In [19]:
print("Array :\n",a7)
sum_ele = np.sum(a7)
print("Sum of all elements:", sum_ele)

Array :
 [[0.88027929 0.03105268 0.40805506 0.93893567]
 [0.84907711 0.75613408 0.67579054 0.90894346]
 [0.5525453  0.91430799 0.8430257  0.54713275]
 [0.82911277 0.6207448  0.09741423 0.77844644]]
Sum of all elements: 10.630997860763275


#8) Given the array arr=np.array([1,2,3,4]), add 10 to each element and multipy the result by 2.

In [ ]:
arr=np.array([1,2,3,4])
print("Array :",arr)
arr=(arr+10)*2
print("After adding 10 to each element and multipy the result by 2 :",arr)

Array : [1 2 3 4]
After adding 10 to each element and multipy the result by 2 : [22 24 26 28]


#9) Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3,4,5) with random integers ranging from 1 to 100. Perform the following:

In [12]:
arr=np.random.randint(1,101,size=(3,4,5))

##a) Extract the second "layer" (i.e., the second 2D array) in the first first dimension.


In [13]:
print("Array :\n",arr)
print("The Second Layer of Array :\n",arr[1])

Array :
 [[[89 23 36 26 52]
  [88 89 69 58 31]
  [32 60  5 12 14]
  [71 34 73 63 51]]

 [[ 1 11 95 19 27]
  [23  2 16 90 59]
  [53 37 80  9 93]
  [38 98 61 98 84]]

 [[61 52 97 24 19]
  [84 45 17 81 60]
  [33 26 35 45 62]
  [45  8 67 89 17]]]
The Second Layer of Array :
 [[ 1 11 95 19 27]
 [23  2 16 90 59]
 [53 37 80  9 93]
 [38 98 61 98 84]]


##b) Extract the first two rows and the last three columns from each "layer".

In [14]:
print("Array :\n",arr)
sarr=arr[:,:2,2:]
print("The first two rows and the last three columns from each layer of Array :\n",sarr)

Array :
 [[[89 23 36 26 52]
  [88 89 69 58 31]
  [32 60  5 12 14]
  [71 34 73 63 51]]

 [[ 1 11 95 19 27]
  [23  2 16 90 59]
  [53 37 80  9 93]
  [38 98 61 98 84]]

 [[61 52 97 24 19]
  [84 45 17 81 60]
  [33 26 35 45 62]
  [45  8 67 89 17]]]
The first two rows and the last three columns from each layer of Array :
 [[[36 26 52]
  [69 58 31]]

 [[95 19 27]
  [16 90 59]]

 [[97 24 19]
  [17 81 60]]]


##c) Replace all elements divisible by 3 with -1.

In [15]:
print("Array :\n",arr)
arr[arr%3==0]=-1
print("After replacing all elements divisible by 3 with -1 :\n",arr)

Array :
 [[[89 23 36 26 52]
  [88 89 69 58 31]
  [32 60  5 12 14]
  [71 34 73 63 51]]

 [[ 1 11 95 19 27]
  [23  2 16 90 59]
  [53 37 80  9 93]
  [38 98 61 98 84]]

 [[61 52 97 24 19]
  [84 45 17 81 60]
  [33 26 35 45 62]
  [45  8 67 89 17]]]
After replacing all elements divisible by 3 with -1 :
 [[[89 23 -1 26 52]
  [88 89 -1 58 31]
  [32 -1  5 -1 14]
  [71 34 73 -1 -1]]

 [[ 1 11 95 19 -1]
  [23  2 16 -1 59]
  [53 37 80 -1 -1]
  [38 98 61 98 -1]]

 [[61 52 97 -1 19]
  [-1 -1 17 -1 -1]
  [-1 26 35 -1 62]
  [-1  8 67 89 17]]]


#10) Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3,3) with random integers between 1 and 20. Perform the following:

In [7]:
arr=np.random.randint(1,21,size=(3,3))
print(arr)

[[ 7  7  9]
 [19 10 12]
 [ 6 17 17]]


##a) Subtract the mean of each row from its respective elements (row-wise normalization)

In [8]:
print("Array :\n",arr)
r_mean=arr.mean(axis=1,keepdims=True)
norm_mean=arr-r_mean
print("Row-wise Normalized mean :\n",norm_mean)

Array :
 [[ 7  7  9]
 [19 10 12]
 [ 6 17 17]]
Row-wise Normalized mean :
 [[-0.66666667 -0.66666667  1.33333333]
 [ 5.33333333 -3.66666667 -1.66666667]
 [-7.33333333  3.66666667  3.66666667]]


##b) Create a new array by squaring all the elements in arr.

In [10]:
print("Array :\n",arr)
arr2=np.power(arr,2)
print("After Squaring all the elements in array :\n",arr2)

Array :
 [[ 7  7  9]
 [19 10 12]
 [ 6 17 17]]
After Squaring all the elements in array :
 [[ 49  49  81]
 [361 100 144]
 [ 36 289 289]]


##c) Find the indicies of the top 3 maximum values in the entire array.

In [11]:
print("Array :\n",arr)
f_arr=arr.flatten()
s_arr=np.argsort(f_arr)[6:]
r=s_arr//arr.shape[1]
c=s_arr%arr.shape[1]
top3=list(zip(r,c))
print("Top 3 maximum values indicies :\n",top3)

Array :
 [[ 7  7  9]
 [19 10 12]
 [ 6 17 17]]
Top 3 maximum values indicies :
 [(2, 1), (2, 2), (1, 0)]
