<a href="https://colab.research.google.com/github/K-R-Reddy/MachineLearning/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#1) Perform arithmetic operations on NumPy arrays.

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
print("Array 1 :",a1,"\nArray 2 :",a2)
print("Addition :",a1+a2)
print("Subtraction :",a1-a2)
print("Multiplication :",a1*a2)
print("Division :",a1/a2)
print("Remainder :",a1%a2)


Array 1 : [1 2 3 4 5] 
Array 2 : [ 6  7  8  9 10]
Addition : [ 7  9 11 13 15]
Subtraction : [-5 -5 -5 -5 -5]
Multiplication : [ 6 14 24 36 50]
Division : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Remainder : [1 2 3 4 5]


#2) Write a script to compute the mean and standard deviation of a NumPy array.
numpy.mean(array_name) : It is used to find Mean of the array.<br>
numpy.std(array_name) : It is used to find the Standard deviation of the array.

In [ ]:
a3=np.array([1,2,3,4,5])
m=np.mean(a3)
s=np.std(a3)
print("Array :",a3)
print("Mean :",m)
print("Standard deviation : ",s)

Array : [1 2 3 4 5]
Mean : 3.0
Standard deviation :  1.4142135623730951


#3) Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
a4=np.array(range(10,51,5))
print("Array :",a4)

Array : [10 15 20 25 30 35 40 45 50]


#4) Reshape the array into a 2x4 matrix


In [ ]:
a5=np.array([1,2,3,4,5,6,7,8])
print("Array :",a5)
ra5=a5.reshape(2,4)
print("After reshape Array :\n",ra5)

Array : [1 2 3 4 5 6 7 8]
After reshape Array :
 [[1 2 3 4]
 [5 6 7 8]]


#5) Given the arr=np.array([[1,2,3],[4,5,6],[7,8,9]]):

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

##a) Extract the sub-matrix containing the last two rows and first two columns.

In [ ]:
sm=arr[1: , :2]
print("Matrix :\n",arr)
print("Sub Matrix :\n",sm)

Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub Matrix :
 [[4 5]
 [7 8]]


##b) Replace all elements greater than 4 and 0.

In [ ]:
arr[arr>4]=0
print("After Replacing with Zeros :")
print(arr)

After Replacing with Zeros :
[[1 2 3]
 [4 0 0]
 [0 0 0]]


#6) Create two 1D arrays:
####a=np.array([1,2,3])
####b=np.array([4,5,6])
#Perform element-wise addition, multiplication, and division.

In [5]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Array 1 :",a,"\nArray 2 :",b)
print("Addition :",np.add(a,b))
print("Multiplication :",np.multiply(a,b))
print("Division :",np.divide(a,b))

Array 1 : [1 2 3] 
Array 2 : [4 5 6]
Addition : [5 7 9]
Multiplication : [ 4 10 18]
Division : [0.25 0.4  0.5 ]


#7) Create a random NumPy array of size(4,4).Compute:

In [ ]:
a7=np.random.rand(4,4)
print(a7)

[[0.58255949 0.91412744 0.74254131 0.94571165]
 [0.82996845 0.5550818  0.69387494 0.93156582]
 [0.4954466  0.14463484 0.75153474 0.4362357 ]
 [0.21225906 0.3248896  0.24744566 0.46617736]]


##a) Mean of each column

In [ ]:
m2=np.mean(a7,axis=0)
print("Mean :",m2)

Mean : [0.5300584  0.48468342 0.60884916 0.69492263]


##b) Maximum value of the entire array.

In [ ]:
max_value=np.max(a7)
print("Maximum value of the entire array :",max_value)

Maximum value of the entire array : 0.9457116508514475


##c) Sum of all elements.

In [ ]:
sum_ele = np.sum(a7)
print("Sum of all elements:", sum_ele)

Sum of all elements: 9.27405444805826


#8) Given the array arr=np.array([1,2,3,4]), add 10 to each element and multipy the result by 2.

In [ ]:
arr=np.array([1,2,3,4])
print("Array :",arr)
arr=(arr+10)*2
print("After adding 10 to each element and multipy the result by 2 :",arr)

Array : [1 2 3 4]
After adding 10 to each element and multipy the result by 2 : [22 24 26 28]


#9) Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3,4,5) with random integers ranging from 1 to 100. Perform the following:

In [ ]:
arr=np.random.randint(1,101,size=(3,4,5))

##a) Extract the second "layer" (i.e., the second 2D array) in the first first dimension.


In [ ]:
print("Array :\n",arr)
print("The Second Layer of Array :\n",arr[1])

Array :
 [[[ 20  59  74  41  87]
  [ 26   5  59  37   3]
  [ 46  22  65  96  88]
  [ 27  40  26  75  29]]

 [[ 81  74  20  71  86]
  [ 78  53  97  40  98]
  [ 39  78  51 100  55]
  [ 78  82  59   1  40]]

 [[ 88  85  62   1  54]
  [ 38  91  25  76  75]
  [ 96  72  76  63  13]
  [ 40  11  57  66  48]]]
The Second Layer of Array :
 [[ 81  74  20  71  86]
 [ 78  53  97  40  98]
 [ 39  78  51 100  55]
 [ 78  82  59   1  40]]


##b) Extract the first two rows and the last three columns from each "layer".

In [ ]:
print("Array :\n",arr)
sarr=arr[:,:2,2:]
print("The first two rows and the last three columns from each layer of Array :\n",sarr)

Array :
 [[[ 32  92  53  19  11]
  [ 67  65  55   1  26]
  [  7  39  91  87  43]
  [  1  84 100   2   7]]

 [[ 46  37  93  65  99]
  [ 15  98  33  85  45]
  [ 64  67  84  16  42]
  [ 52  52  18  46  45]]

 [[ 92  24  61  86  93]
  [  9  68  44  19  77]
  [ 70  40  83  50  82]
  [  8  50  32  64  85]]]
The first two rows and the last three columns from each layer of Array :
 [[[53 19 11]
  [55  1 26]]

 [[93 65 99]
  [33 85 45]]

 [[61 86 93]
  [44 19 77]]]


##c) Replace all elements divisible by 3 with -1.

In [ ]:
print(arr)
arr[arr%3==0]=-1
print("After replacing all elements divisible by 3 with -1 :\n",arr)

[[[ 32  92  53  19  11]
  [ 67  65  55   1  26]
  [  7  39  91  87  43]
  [  1  84 100   2   7]]

 [[ 46  37  93  65  99]
  [ 15  98  33  85  45]
  [ 64  67  84  16  42]
  [ 52  52  18  46  45]]

 [[ 92  24  61  86  93]
  [  9  68  44  19  77]
  [ 70  40  83  50  82]
  [  8  50  32  64  85]]]
After replacing all elements divisible by 3 with -1 :
 [[[ 32  92  53  19  11]
  [ 67  65  55   1  26]
  [  7  -1  91  -1  43]
  [  1  -1 100   2   7]]

 [[ 46  37  -1  65  -1]
  [ -1  98  -1  85  -1]
  [ 64  67  -1  16  -1]
  [ 52  52  -1  46  -1]]

 [[ 92  -1  61  86  -1]
  [ -1  68  44  19  77]
  [ 70  40  83  50  82]
  [  8  50  32  64  85]]]


#10) Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3,3) with random integers between 1 and 20. Perform the following:

In [ ]:
arr=np.random.randint(1,21,size=(3,3))
print(arr)

[[20  1 20]
 [13 10 15]
 [ 8 20 17]]


##a) Subtract the mean of each row from its respective elements (row-wise normalization)

In [ ]:
print(arr)
r_mean=arr.mean(axis=1,keepdims=True)
norm_mean=arr-r_mean
print("Row-wise Normalized mean :\n",norm_mean)

[[20  1 20]
 [13 10 15]
 [ 8 20 17]]
Row-wise Normalized mean :
 [[  6.33333333 -12.66666667   6.33333333]
 [  0.33333333  -2.66666667   2.33333333]
 [ -7.           5.           2.        ]]


##b) Create a new array by squaring all the elements in arr.

In [ ]:
print(arr)
arr2=np.power(arr,2)
print(arr2)

[[20  1 20]
 [13 10 15]
 [ 8 20 17]]
[[400   1 400]
 [169 100 225]
 [ 64 400 289]]


##c) Find the indicies of the top 3 maximum values in the entire array.

In [ ]:
print(arr)
f_arr=arr.flatten()
s_arr=np.argsort(f_arr)[6:]
r=s_arr//arr.shape[1]
c=s_arr%arr.shape[1]
top3=list(zip(r,c))
print("Top 3 maximum values indicies :\n",top3)

[[20  1 20]
 [13 10 15]
 [ 8 20 17]]
Top 3 maximum values indicies :
 [(0, 0), (0, 2), (2, 1)]
