<a href="https://colab.research.google.com/github/K-R-Reddy/MachineLearning/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#1) Perform arithmetic operations on NumPy arrays.

In [46]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
print("Array 1 :",a1,"\nArray 2 :",a2)
print("Addition :",a1+a2)
print("Subtraction :",a1-a2)
print("Multiplication :",a1*a2)
print("Division :",a1/a2)
print("Remainder :",a1%a2)


Array 1 : [1 2 3 4 5] 
Array 2 : [ 6  7  8  9 10]
Addition : [ 7  9 11 13 15]
Subtraction : [-5 -5 -5 -5 -5]
Multiplication : [ 6 14 24 36 50]
Division : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Remainder : [1 2 3 4 5]


#2) Write a script to compute the mean and standard deviation of a NumPy array.

In [11]:
a3=np.array([1,2,3,4,5])
m=np.mean(a3)
s=np.std(a3)
print("Array :",a3)
print("Mean :",m)
print("Standard deviation : ",s)

Array : [1 2 3 4 5]
Mean : 3.0
Standard deviation :  1.4142135623730951


#3) Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [21]:
a4=np.array(range(10,51,5))
print("Array :",a4)

Array : [10 15 20 25 30 35 40 45 50]


#4) Reshape the array into a 2x4 matrix


In [19]:
a5=np.array([1,2,3,4,5,6,7,8])
print("Array :",a5)
ra5=a5.reshape(2,4)
print("After reshape Array :\n",ra5)

Array : [1 2 3 4 5 6 7 8]
After reshape Array :
 [[1 2 3 4]
 [5 6 7 8]]


#5) Given the arr=np.array([[1,2,3],[4,5,6],[7,8,9]]):

In [37]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

##a) Extract the sub-matrix containing the last two rows and first two columns.

In [25]:
sm=arr[1: , :2]
print("Matrix :\n",arr)
print("Sub Matrix :\n",sm)

Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sub Matrix :
 [[4 5]
 [7 8]]


##b) Replace all elements greater than 4 and 0.

In [39]:
arr[arr>4]=0
print("After Replacing with Zeros :")
print(arr)

After Replacing with Zeros :
[[1 2 3]
 [4 0 0]
 [0 0 0]]


#6) Create two 1D arrays:
####a=np.array([1,2,3])
####b=np.array([4,5,6])
#Perform element-wise addition, multiplication, and division.

In [43]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Array 1 :",a,"\nArray 2 :",b)
print("Addition :",np.add(a,b))
print("Subraction :",np.subtract(a,b))
print("Division :",np.divide(a,b))

Array 1 : [1 2 3] 
Array 2 : [4 5 6]
Addition : [5 7 9]
Subraction : [-3 -3 -3]
Division : [0.25 0.4  0.5 ]


#7) Create a random NumPy array of size(4,4).Compute:

In [48]:
a7=np.random.rand(4,4)
print(a7)

[[0.01099714 0.63892045 0.27811307 0.09963669]
 [0.06780047 0.66645577 0.46147728 0.63378671]
 [0.06302835 0.01235678 0.11759742 0.24237085]
 [0.57000187 0.82111674 0.87097537 0.18457777]]


##a) Mean of each column

In [57]:
m2=np.mean(a7,axis=0)
print("Mean :",m2)

Mean : [0.17795695 0.53471243 0.43204079 0.290093  ]


##b) Maximum value of the entire array.

In [58]:
max_value=np.max(a7)
print("Maximum value of the entire array :",max_value)

Maximum value of the entire array : 0.870975372722606


##c) Sum of all elements.

In [72]:
sum_ele = np.sum(a7)
print("Sum of all elements:", sum_ele)

Sum of all elements: 5.739212707398519


#8) Given the array arr=np.array([1,2,3,4]), add 10 to each element and multipy the result by 2.

In [62]:
arr=np.array([1,2,3,4])
print("Array :",arr)
arr=(arr+10)*2
print("After adding 10 to each element and multipy the result by 2 :",arr)

Array : [1 2 3 4]
After adding 10 to each element and multipy the result by 2 : [22 24 26 28]


#9) Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3,4,5) with random integers ranging from 1 to 100. Perform the following:

In [63]:
arr=np.random.randint(1,101,size=(3,4,5))

[[[ 20  59  74  41  87]
  [ 26   5  59  37   3]
  [ 46  22  65  96  88]
  [ 27  40  26  75  29]]

 [[ 81  74  20  71  86]
  [ 78  53  97  40  98]
  [ 39  78  51 100  55]
  [ 78  82  59   1  40]]

 [[ 88  85  62   1  54]
  [ 38  91  25  76  75]
  [ 96  72  76  63  13]
  [ 40  11  57  66  48]]]


##a) Extract the second "layer" (i.e., the second 2D array) in the first first dimension.


In [64]:
print("Array :\n",arr)
print("The Second Layer of Array :\n",arr[1])

Array :
 [[[ 20  59  74  41  87]
  [ 26   5  59  37   3]
  [ 46  22  65  96  88]
  [ 27  40  26  75  29]]

 [[ 81  74  20  71  86]
  [ 78  53  97  40  98]
  [ 39  78  51 100  55]
  [ 78  82  59   1  40]]

 [[ 88  85  62   1  54]
  [ 38  91  25  76  75]
  [ 96  72  76  63  13]
  [ 40  11  57  66  48]]]
The Second Layer of Array :
 [[ 81  74  20  71  86]
 [ 78  53  97  40  98]
 [ 39  78  51 100  55]
 [ 78  82  59   1  40]]


##b) Extract the first two rows and the last three columns from each "layer".

In [68]:
print("Array :\n",arr)
sarr=arr[:,:2,2:]
print("The first two rows and the last three columns from each layer of Array :\n",sarr)

Array :
 [[[ 20  59  74  41  87]
  [ 26   5  59  37   3]
  [ 46  22  65  96  88]
  [ 27  40  26  75  29]]

 [[ 81  74  20  71  86]
  [ 78  53  97  40  98]
  [ 39  78  51 100  55]
  [ 78  82  59   1  40]]

 [[ 88  85  62   1  54]
  [ 38  91  25  76  75]
  [ 96  72  76  63  13]
  [ 40  11  57  66  48]]]
The first two rows and the last three columns from each layer of Array :
 [[[74 41 87]
  [59 37  3]]

 [[20 71 86]
  [97 40 98]]

 [[62  1 54]
  [25 76 75]]]


##c) Replace all elements divisible by 3 with -1.

In [69]:
print(arr)
arr[arr%3==0]=-1
print("After replacing all elements divisible by 3 with -1 :\n",arr)

[[[ 20  59  74  41  87]
  [ 26   5  59  37   3]
  [ 46  22  65  96  88]
  [ 27  40  26  75  29]]

 [[ 81  74  20  71  86]
  [ 78  53  97  40  98]
  [ 39  78  51 100  55]
  [ 78  82  59   1  40]]

 [[ 88  85  62   1  54]
  [ 38  91  25  76  75]
  [ 96  72  76  63  13]
  [ 40  11  57  66  48]]]
After replacing all elements divisible by 3 with -1 :
 [[[ 20  59  74  41  -1]
  [ 26   5  59  37  -1]
  [ 46  22  65  -1  88]
  [ -1  40  26  -1  29]]

 [[ -1  74  20  71  86]
  [ -1  53  97  40  98]
  [ -1  -1  -1 100  55]
  [ -1  82  59   1  40]]

 [[ 88  85  62   1  -1]
  [ 38  91  25  76  -1]
  [ -1  -1  76  -1  13]
  [ 40  11  -1  -1  -1]]]


#10) Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3,3) with random integers between 1 and 20. Perform the following:

In [70]:
arr=np.random.randint(1,21,size=(3,3))
print(arr)

[[ 2 11 12]
 [10  7 16]
 [15 20 14]]


##a) Subtract the mean of each row from its respective elements (row-wise normalization)

In [74]:
print(arr)
r_mean=arr.mean(axis=1,keepdims=True)
norm_mean=arr-r_mean
print("Row-wise Normalized mean :\n",norm_mean)

[[ 2 11 12]
 [10  7 16]
 [15 20 14]]
Row-wise Normalized mean :
 [[-6.33333333  2.66666667  3.66666667]
 [-1.         -4.          5.        ]
 [-1.33333333  3.66666667 -2.33333333]]


##b) Create a new array by squaring all the elements in arr.

In [71]:
print(arr)
arr2=np.power(arr,2)
print(arr2)

[[ 2 11 12]
 [10  7 16]
 [15 20 14]]
[[  4 121 144]
 [100  49 256]
 [225 400 196]]


##c) Find the indicies of the top 3 maximum values in the entire array.

In [81]:
print(arr)
f_arr=arr.flatten()
s_arr=np.argsort(f_arr)[6:]
r=s_arr//arr.shape[1]
c=s_arr%arr.shape[1]
top3=list(zip(r,c))
print("Top 3 maximum values indicies :\n",top3)

[[ 2 11 12]
 [10  7 16]
 [15 20 14]]
Top 3 maximum values indicies :
 [(2, 0), (1, 2), (2, 1)]
